### ISSUE TITLE
你这个文件上传倒是没啥问题，但是你的文件下载和删除不对啊

### ISSUE THREAD

**Issue by YAGAMIL** [ZongweiBai/spring-boot-in-action#1]
没看到你的代码里下载和删除这一块儿有和minio服务器操作和访问

**Comment by ZongweiBai** [comment]
> 
> 
> 没看到你的代码里下载和删除这一块儿有和minio服务器操作和访问

都调用了 `MinIORepository.java` 里的方法进行了操作，你可以更新一下代码。
