### ISSUE TITLE
我把你的项目拉下来构建跑了一遍，下载确实有问题，不能用

### ISSUE THREAD

**Issue by YAGAMIL** [ZongweiBai/spring-boot-in-action#2]

**Comment by ZongweiBai** [comment]
下载的逻辑已经补上，之前是因为临时文件夹没有创建导致下载的失败

**Comment by YAGAMIL** [comment]
Okay，感谢，一会儿再看看，对于JDK14的新特性，你有啥看法

**Comment by ZongweiBai** [comment]
多了一些语法糖，方便了日常的开发，在我看来最有用的是对NullPointException的优化，这样查问题就更方便了。我个人是习惯自己尝试下新的东西不至于太落后，但实际的生产还是使用JDK8。

**Comment by YAGAMIL** [comment]
我生产环境在用JDK11了，本来用阿里的龙井，但是发现有问题，改回oracle就正常了
